---
- name: Check ansible version
  import_playbook: ansible_version.yml

- hosts: all
  gather_facts: false
  tags: always
  tasks:
    - name: "Set up proxy environment"
      set_fact:
        proxy_env:
          http_proxy: "{{ http_proxy | default ('') }}"
          HTTP_PROXY: "{{ http_proxy | default ('') }}"
          https_proxy: "{{ https_proxy | default ('') }}"
          HTTPS_PROXY: "{{ https_proxy | default ('') }}"
          no_proxy: "{{ no_proxy | default ('') }}"
          NO_PROXY: "{{ no_proxy | default ('') }}"
      no_log: true

- hosts: bastion[0]
  gather_facts: False
  roles:
    - { role: kubespray-defaults }
    - { role: bastion-ssh-config, tags: ["localhost", "bastion"] }

- hosts: all
  gather_facts: False
  tasks:
    - name: Set fact
      set_fact:
        rsa_cert_path: "/kubespray/config/ssh_cert"

    - name: Gen ssh certs
      shell: |
        rm -rf {{ rsa_cert_path }}/id_rsa* && ssh-keygen -t rsa -f {{ rsa_cert_path }}/id_rsa  -P ""
      delegate_to: localhost
      run_once: true

    - name: ssh-copy
      authorized_key: user={{ ansible_user }} key="{{ lookup('file', '{{ rsa_cert_path }}/id_rsa.pub') }}"
