---
- name: Multus | Copy manifest files
  copy:
    src: "{{ item.file }}"
    dest: "{{ kube_config_dir }}"
  with_items:
    - {name: multus-crd, file: multus-crd.yml, type: customresourcedefinition}
    - {name: network-crd, file: network-crd.yml, type: customresourcedefinition}
    - {name: multus-cm, file: multus-cm.yml, type: configmap}
    - {name: multus-serviceaccount, file: multus-serviceaccount.yml, type: serviceaccount}
    - {name: multus-clusterrole, file: multus-clusterrole.yml, type: clusterrole}
    - {name: multus-clusterrolebinding, file: multus-clusterrolebinding.yml, type: clusterrolebinding}
    - {name: network-agent-rbac, file: network-agent-rbac.yml, type: rbac}
  register: multus_manifest_1

- name: Multus | Copy manifest templates
  template:
    src: "{{ item.file }}.j2"
    dest: "{{ kube_config_dir }}/{{ item.file }}"
  with_items:
    - {name: network-instances, file: network-instances.yml, type: network}
    - {name: multus-daemonset, file: multus-daemonset.yml, type: daemonset}
    - {name: fixedip-ipam-server, file: fixedip-ipam-server.yml, type: deployment}
    - {name: network-agent-ds, file: network-agent-ds.yml, type: daemonset}
  register: multus_manifest_2
