---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fixedip-ipam-server
rules:
  - apiGroups:
      - networking.containeros.dev
    resources:
      - networks
    verbs:
      - watch
      - get
      - list
  - apiGroups:
      - networking.containeros.dev
    resources:
      - ipresources
    verbs:
      - create
      - update
      - delete
      - get
      - list
      - watch
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - validatingwebhookconfigurations
    verbs:
      - create
      - update
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - watch
      - update
      - list
      - get
  - apiGroups:
      - batch
    resources:
      - cronjobs
      - jobs
    verbs:
      - watch
      - list
      - get
      - update
  - apiGroups:
      - apps
    resources:
      - replicasets
      - statefulsets
      - deployments
    verbs:
      - watch
      - list
      - get
      - update
  - apiGroups:
      - policy
    resources:
      - podsecuritypolicies
    verbs:
      - use
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - update
      - create
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fixedip-ipam-server
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fixedip-ipam-server
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fixedip-ipam-server
subjects:
  - kind: ServiceAccount
    name: fixedip-ipam-server
    namespace: kube-system
