---
kind: ConfigMap
apiVersion: v1
metadata:
  name: multus-cni-config
  namespace: kube-system
  labels:
    tier: node
    app: multus
data:
  cni-conf.json: |
    {
      "cniVersion": "0.3.1",
      "name": "multus-cni-network",
      "type": "multus",
      "capabilities": {
        "portMappings": true
      },
      "confDir": "/etc/cni/net.d/",
      "logFile": "/var/log/multus.log",
      "logLevel": "error",
      "clusterNetwork": "k8s-pod-network",
      "defaultNetworks": [],
      "multusNamespace" : "kube-system",
      "kubeconfig": "/etc/cni/net.d/multus.d/multus.kubeconfig"
    }
